name: Ebook Editor - Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'ebook-editor/**'
      - '.github/workflows/ebook-editor-deploy.yml'
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  S3_BUCKET: expotoworld-ebook-website
  CLOUDFRONT_DISTRIBUTION_ID: E25UL5QH3I1VIU
  NODE_VERSION: '18'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ebook-editor/package-lock.json

      - name: Install dependencies
        working-directory: ebook-editor
        run: npm ci

      - name: Build application
        working-directory: ebook-editor
        run: npm run build
        env:
          VITE_API_BASE: https://device-api.expotoworld.com
          VITE_AUTH_BASE: https://device-api.expotoworld.com

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::834076182408:role/GitHubActionsECRPush-expotoworld
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        working-directory: ebook-editor
        run: |
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }}/ \
            --delete \
            --cache-control "public, max-age=31536000, immutable" \
            --exclude "*.html" \
            --exclude "*.json"
          
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }}/ \
            --exclude "*" \
            --include "*.html" \
            --include "*.json" \
            --cache-control "public, max-age=0, must-revalidate"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*" \
            --region us-east-1

      - name: Deployment summary
        run: |
          echo "✅ Ebook Editor deployed successfully!"
          echo "📦 S3 Bucket: ${{ env.S3_BUCKET }}"
          echo "🌐 CloudFront Distribution: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}"
          echo "🔗 URL: https://huashangdao.expotoworld.com"

